pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "vinh14124374/app-chat-backend:${BUILD_NUMBER}"
        DOCKER_CRED = credentials('dockerhub')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'devVinh', url: 'https://github.com/vinh1412/Chat_BE.git', credentialsId: 'github-cred'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t vinh14124374/app-chat-backend .'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    sh 'echo $DOCKER_CRED_PSW | docker login -u $DOCKER_CRED_USR --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                script {
                    // Dừng và xóa container hiện tại (nếu có)
                    sh '''
                    docker stop app-chat-backend || true
                    docker rm app-chat-backend || true
                    '''
                    // Chạy container mới
                    sh "docker run -d -p 8080:8080 --name app-chat-backend ${DOCKER_IMAGE}"
                }
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}