

spring:
  application:
    name: ChatAppACE_Group03
  config:
    import: optional:file:.env[.properties]  # Import từ file .env
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}  # Lấy từ .env
      database: chatapp

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
rsa:
  rsa-private-key: ${RSA_PRIVATE_KEY}  # Lấy từ .env
  rsa-public-key: ${RSA_PUBLIC_KEY} # Lấy từ .env

aws:
  region: ${AWS_REGION}
  sns:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}